bucket_prefix = "terraform-devopsdirective-demo-webapp"
domain_zone   = "timmytandian.com"
domain_webroot= "tf-demo.timmytandian.com"
db_name       = "mydb"
db_user       = "foo"
# db_pass = "foobarbaz"
